a=int(input("Dati nr de oua obtinute de la 1-a gaina : "))
b=int(input("Dati nr de oua obtinute de la 2-a gaina : "))
c=int(input("Dati nr de oua obtinute de la 3-a gaina : "))
d=int(input("Dati nr de oua obtinute de la 4-a gaina : "))
print("Intr-o saptamana se obtin",a+b+c+d,"oua")
